services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatPayBusifavorBundle\Command\:
    resource: '../../Command/'
  WechatPayBusifavorBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatPayBusifavorBundle\Procedure\:
    resource: '../../Procedure/'
  WechatPayBusifavorBundle\Repository\:
    resource: '../../Repository/'
  WechatPayBusifavorBundle\Service\:
    resource: '../../Service/'

  # Explicit service definitions for testing
  wechat_pay_busifavor.service.busifavor:
    class: WechatPayBusifavorBundle\Service\BusifavorService
    public: true

  wechat_pay_busifavor.repository.stock:
    class: WechatPayBusifavorBundle\Repository\StockRepository
    public: true

  wechat_pay_busifavor.repository.coupon:
    class: WechatPayBusifavorBundle\Repository\CouponRepository
    public: true

  wechat_pay_busifavor.command.list_user_coupons:
    class: WechatPayBusifavorBundle\Command\ListUserCouponsCommand
    public: true

  wechat_pay_busifavor.command.sync_stock:
    class: WechatPayBusifavorBundle\Command\SyncStockCommand
    public: true
