services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    WechatPayBusifavorBundle\DataFixtures\:
        resource: '../../DataFixtures/*'
        tags: ['doctrine.fixture.orm']